### ISSUE TITLE
Runtime Error after select image from Gallary

### ISSUE THREAD

**Issue by prashant31191** [phamxuanlu/PhotoEffectsEditor#1]
About Device -Version 5.1 (Moto e2)

android.imageeditor E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.alienage.android.imageeditor, PID: 29740
                                                                                  java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/os/AsyncTaskCompat;
                                                                                      at com.adobe.creativesdk.aviary.AdobeImageEditorActivityAbstract.loadTools(AdobeImageEditorActivityAbstract.java:760)
                                                                                      at com.adobe.creativesdk.aviary.AdobeImageEditorActivityAbstract.onPostCreate(AdobeImageEditorActivityAbstract.java:579)
                                                                                      at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1210)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2321)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
                                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:155)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                                                                   Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.os.AsyncTaskCompat" on path: DexPathList[[zip file "/data/app/com.alienage.android.imageeditor-1/base.apk"],nativeLibraryDirectories=[/data/app/com.alienage.android.imageeditor-1/lib/arm, /vendor/lib, /system/lib]]
                                                                                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                      at com.adobe.creativesdk.aviary.AdobeImageEditorActivityAbstract.loadTools(AdobeImageEditorActivityAbstract.java:760) 
                                                                                      at com.adobe.creativesdk.aviary.AdobeImageEditorActivityAbstract.onPostCreate(AdobeImageEditorActivityAbstract.java:579) 
                                                                                      at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1210) 
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2321) 
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
                                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:155) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:135) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
                                                                                  	Suppressed: java.lang.ClassNotFoundException: android.support.v4.os.AsyncTaskCompat
                                                                                      at java.lang.Class.classForName(Native Method)
                                                                                      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                      at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                      		... 15 more
                                                                                   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by pawandeepka** [comment]
Did you get any solution?
